name: Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      vsixPath: ${{ steps.packageExtension.outputs.vsixPath }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Package Extension
        id: packageExtension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: stub
          dryRun: true

      - name: Upload Extension Package as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: ${{ steps.packageExtension.outputs.vsixPath }}

  publish:
    name: Publish Extension
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: extension

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            ${{ needs.build.outputs.vsixPath }}

      - name: Publish to Visual Studio Marketplace
        uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_PAT }}
