name: Creete Relese

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      vsixPath: ${{ steps.packageExtension.outputs.vsixPath }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Install Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Package Extension
        id: packageExtension
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: stub
          dryRun: true

      - name: Upload Extension Package as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: ${{ steps.packageExtension.outputs.vsixPath }}

      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: extension

      - name: List Artifacts
        run: ls -R

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            ${{ outputs.vsixPath }}
